version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "Blacklist-API-fargate-service"
          ContainerPort: 8000
hooks:
  BeforeInstall:
    - location: scripts/fail_script.sh
      timeout: 300
      runas: root
